_wandb:
    value:
        cli_version: 0.21.4
        e:
            xsefcbnda9kkaco3vbhyisa8ccb98tfd:
                codePath: client/global_training/main_global_with_wandb.py
                codePathLocal: main_global_with_wandb.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1081101176832"
                        used: "46739562496"
                email: umarbalak35@gmail.com
                executable: /home/umarb/SecureFL/.venv/bin/python3
                git:
                    commit: 1e3efd57e1a178de26a5af11a032880e38ba4a4c
                    remote: git@github.com:UmarBalak/SecureFL.git
                host: NoteBook
                memory:
                    total: "8178028544"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/umarb/SecureFL/client/global_training/main_global_with_wandb.py
                python: CPython 3.10.17
                root: /home/umarb/SecureFL/client/global_training
                startedAt: "2025-09-27T09:43:17.107882Z"
                writerId: xsefcbnda9kkaco3vbhyisa8ccb98tfd
        m:
            - "1": fl_round
              "6":
                - 3
              "7": []
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "2": epoch/*
              "5": 2
              "6":
                - 1
              "7": []
            - "2": global_model/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": per_class/*
              "5": 1
              "6":
                - 1
              "7": []
            - "2": client_contribution/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.17
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 3
                - 7
                - 13
                - 15
                - 16
                - 38
                - 39
                - 61
            "4": 3.10.17
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
aggregation_strategy:
    value: weighted_average
architecture:
    value:
        - 256
        - 256
artifacts_dir:
    value: artifacts
batch_size:
    value: 128
class_names:
    value:
        - Backdoor
        - DDoS_HTTP
        - DDoS_ICMP
        - DDoS_TCP
        - DDoS_UDP
        - Fingerprinting
        - MITM
        - Normal
        - Password
        - Port_Scanning
        - Ransomware
        - SQL_injection
        - Uploading
        - Vulnerability_scanner
        - XSS
data_distribution:
    value: global_balanced
dataset:
    value: ML-Edge-IIoT
delta:
    value: 1e-05
differential_privacy:
    value: true
epochs:
    value: 10
epsilon:
    value: 1
features:
    value: 25
fl_algorithm:
    value: FedAvg
fl_setup:
    value: initial_global_model
learning_rate:
    value: 5e-05
min_clients_per_round:
    value: 2
model_architecture:
    value:
        - 256
        - 256
num_classes:
    value: 15
random_state:
    value: 42
test_data_path_pattern:
    value: ./DATA/DATA_VARIABLE/global_test.csv
total_clients:
    value: 10
train_data_path_pattern:
    value: ./DATA/DATA_VARIABLE/global_train.csv
wandb_integration:
    value: modern_callbacks
